workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    # CI_PIPELINE_SOURCE reference:
    # | Source              | Meaning |
    # | push                | A Git push created the pipeline. This includes branch pushes and tag pushes. |
    # | merge_request_event | GitLab created the pipeline for a merge request. |
    # | schedule            | A GitLab CI schedule created it. |
    # | api                 | Someone or something called the GitLab pipeline API, like our bot does. |
    # | web                 | A user clicked Run pipeline in the GitLab web UI. |
    # | trigger             | A pipeline trigger token created it. This is different from the normal API with a PAT. |
    # | pipeline            | A downstream multi-project pipeline created it. For example, project A triggers project B. |
    # | parent_pipeline     | A child pipeline created from a parent pipeline in the same project. Usually from trigger: include / child pipeline YAML. |
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "api"'
      when: always
    - when: never

default:
  interruptible: true

include:
  - local: ci/common/rules.yml
  - local: ci/common/images.yml
  - local: ci/common/matrices.yml
  - local: ci/common/cudnn.yml
  - local: ci/stages/manual/jobs.yml
  - local: ci/stages/analysis/jobs.yml
  - local: ci/stages/build/jobs.yml
  - local: ci/stages/sanitizer_tests/jobs.yml
  - local: ci/stages/cpp_samples/jobs.yml
  - local: ci/stages/oss_tests/jobs.yml
  - local: ci/stages/frost_tests/jobs.yml
  - local: ci/stages/python_samples/jobs.yml
  - local: ci/stages/python_tests/jobs.yml
  - local: ci/stages/multi_gpu_tests/jobs.yml
  - local: ci/stages/pycudnn_tests/jobs.yml
  - local: ci/stages/l4_graph_runner/jobs.yml
  - local: ci/stages/backend_triggers/jobs.yml
  - local: ci/stages/deploy/jobs.yml
  - local: ci/stages/notify/jobs.yml
  - local: ci/qa_matrix/jobs.yml
    inputs:
      cuda_version: "13.1.0"
      cudnn_version: "9.19.0.56"
    rules:
      - if: $CI_PIPELINE_SOURCE == "schedule"

stages:
  - manual
  - analysis
  - build
  - python_samples
  - cpp_samples
  - oss_tests
  - frost_tests
  - python_tests
  - sanitizer_tests
  - pycudnnTest
  - multi-gpu-run
  - backend_triggers
  - L4_graph_runner
  - deploy
  - notify
