deploy:build_bdist_wheels:
    extends:
        - .pip_wheel_builder_image:template
    tags:
        - wheel_builder
    needs: []
    stage: deploy
    script:
        - ci/stages/deploy/build_pip_wheels.sh
    rules:
        - !reference [.rules:schedule_only, rules]
    artifacts:
        paths:
            - many_linux_wheels/*.whl

.windows_wheel_builder_template:
    tags:
        - windows_wheel_builder
    needs: []
    stage: deploy
    script:
        - if (-not (conda env list | Select-String -Pattern "py${PYTHON_VERSION}")) { if ("${PYTHON_VERSION}" -like "*t*") { conda create -n "py${PYTHON_VERSION}" -y -c conda-forge python-freethreading=${PYTHON_FULL_VERSION} } else { conda create -n "py${PYTHON_VERSION}" -y python=${PYTHON_FULL_VERSION} } }
        - "& C:\\tools\\Anaconda3\\Scripts\\conda.exe init powershell"
        - ". C:\\tools\\Anaconda3\\shell\\condabin\\conda-hook.ps1"
        - "conda activate py${PYTHON_VERSION}"
        - if ("${PYTHON_VERSION}" -like "*t*") { $Env:CL = "/DPy_GIL_DISABLED=1 $Env:CL" }
        - $Env:CUDNN_PATH = "C:\Users\Public\Downloads\cudnn-9.18.1.3"
        - python --version
        - python -m pip wheel --no-deps . -w ./wheels/py${PYTHON_VERSION}
        - conda deactivate
        - $wheel = Get-ChildItem -Path "./wheels/py${PYTHON_VERSION}/*${version}*.whl" | Select-Object -ExpandProperty Name
        - $DATE_FOLDER = Get-Date -Format "yyyy-MM-dd"
        - if ($CI_COMMIT_BRANCH -eq "main") { echo "main branch ${DATE_FOLDER}"; curl.exe -u ${ARTIFACTORY_USER}:${ARTIFACTORY_TOKEN} -T ./wheels/py${PYTHON_VERSION}/${wheel} https://artifactory.nvidia.com/artifactory/hw-cudnn-generic-local/CUDNN/cudnn_frontend/main/${DATE_FOLDER}/${wheel} } elseif (${CI_COMMIT_BRANCH} -eq "develop") {echo "develop branch ${DATE_FOLDER}"; curl.exe -u ${ARTIFACTORY_USER}:${ARTIFACTORY_TOKEN} -T ./wheels/py${PYTHON_VERSION}/${wheel} https://artifactory.nvidia.com/artifactory/hw-cudnn-generic-local/CUDNN/cudnn_frontend/develop/latest/${wheel} } else { echo "${CI_COMMIT_BRANCH}"; echo "Not posting ${wheel} to artifactory"}
    rules:
        - !reference [.rules:schedule_only, rules]
    artifacts:
        paths:
            - wheels/py${PYTHON_VERSION}/*.whl

deploy:build_bdist_wheels_3.14:
    extends: .windows_wheel_builder_template
    variables:
        PYTHON_VERSION: "314"
        PYTHON_FULL_VERSION: "3.14.2"

deploy:build_bdist_wheels_3.14t:
    extends: .windows_wheel_builder_template
    variables:
        PYTHON_VERSION: "314t"
        PYTHON_FULL_VERSION: "3.14.2"

deploy:build_bdist_wheels_3.13:
    extends: .windows_wheel_builder_template
    variables:
        PYTHON_VERSION: "313"
        PYTHON_FULL_VERSION: "3.13.5"

deploy:build_bdist_wheels_3.12:
    extends: .windows_wheel_builder_template
    variables:
        PYTHON_VERSION: "312"
        PYTHON_FULL_VERSION: "3.12.7"

deploy:build_bdist_wheels_3.11:
    extends: .windows_wheel_builder_template
    variables:
        PYTHON_VERSION: "311"
        PYTHON_FULL_VERSION: "3.11.7"

deploy:build_bdist_wheels_3.10:
    extends: .windows_wheel_builder_template
    variables:
        PYTHON_VERSION: "310"
        PYTHON_FULL_VERSION: "3.10.10"

deploy:build_bdist_wheels_3.9:
    extends: .windows_wheel_builder_template
    variables:
        PYTHON_VERSION: "39"
        PYTHON_FULL_VERSION: "3.9.7"

deploy:test_bdist_wheels_ga_cudnn_3.12:
    parallel:
        matrix:
            - ARCH: ["Hopper", "Ampere"]
    tags:
        - ${ARCH}
    needs: ["deploy:build_bdist_wheels"]
    stage: deploy
    extends:
        - .cudnn_ga_image:template
    rules:
        - !reference [.rules:schedule_only, rules]
    script:
        - apt-get install -y wget
        - wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        - dpkg -i cuda-keyring_1.1-1_all.deb
        - rm cuda-keyring_1.1-1_all.deb
        - apt-get update
        - apt-get install -y software-properties-common
        - add-apt-repository ppa:deadsnakes/ppa
        - apt-get update
        - apt-get -y install python3-pip
        - pip uninstall -y nvidia_cudnn_frontend
        - ls many_linux_wheels/*.whl
        - pip install -v many_linux_wheels/nvidia_cudnn_frontend*cp312*.whl
        - pip install --group dev
        - pip uninstall -y nvidia-cudnn-cu12 # Only removing it because the test is meant for 8907
        - pytest test/python -n 4 -k "not test_mhas and not fe_api and not frost"
