#!/bin/bash
set -e

function display_header() {
    nvidia-smi
    echo "Installed cudnn version" $CUDNN_VERSION_
    echo "Installed cuda version" $CUDA_VERSION_
}

function run_python_tests() {
    export PYTHONPATH=build
    export LD_LIBRARY_PATH=/debug_cudnn/lib64
    
    #Legacy graph test (TODO(@mbreughe): add to a list instead)
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ConvScaleBiasAddRelu2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ConvScaleBiasAddRelu2D_abstract_not_virtual -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ConvReductionRow2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ConvReductionFull2D_AMax_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ScaleBiasReductionCol2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ScaleBiasReductionRow2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ConvReductionCol2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin g -Pout g -Pcomp s -formatAll 1 -rtol 2.1e-2 -atol 5e-2 -minDevVer 800 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ConvScaleBiasAddRelu3D_abstract -dimA 63,48,5,11,9 -filtA 272,48,1,1,1 -x -padA 0,0,0 -convStrideA 1,1,1 -dilationA 1,1,1 -dim 3 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ConvReductionCol3D_abstract -dimA 63,48,5,11,9 -filtA 272,48,1,1,1 -x -padA 0,0,0 -convStrideA 1,1,1 -dilationA 1,1,1 -dim 3 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ConvReductionRow3D_abstract -dimA 63,48,5,11,9 -filtA 272,48,1,1,1 -x -padA 0,0,0 -convStrideA 1,1,1 -dilationA 1,1,1 -dim 3 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ScaleBiasReductionCol3D_abstract -dimA 63,48,5,11,9 -filtA 272,48,1,1,1 -x -padA 0,0,0 -convStrideA 1,1,1 -dilationA 1,1,1 -dim 3 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= ScaleBiasReductionRow3D_abstract -dimA 63,48,5,11,9 -filtA 272,48,1,1,1 -x -padA 0,0,0 -convStrideA 1,1,1 -dilationA 1,1,1 -dim 3 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= DgradAddDreluForkScale2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= DgradReductionRow2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= DgradReductionCol2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin g -Pout g -Pcomp s -formatAll 1 -rtol 2.1e-2 -atol 5e-2 -minDevVer 800 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= DgradAddDreluForkScale3D_abstract -dimA 63,48,5,11,9 -filtA 272,48,1,1,1 -x -padA 0,0,0 -convStrideA 1,1,1 -dilationA 1,1,1 -dim 3 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine 1 -jsonTestName= ScaleBiasReluConv_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 800 -S -b -gpuRef -d 0
    #python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine 1 -jsonTestName= ScaleBiasReluWgrad_abstract -dimA 17,16,28,28 -filtA 80,16,3,3 -x -padA 1,1 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 800 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine 1 -jsonTestName= ScaleBiasReluConv3D_abstract -dimA 63,48,5,11,9 -filtA 272,48,1,1,1 -x -padA 0,0,0 -convStrideA 1,1,1 -dilationA 1,1,1 -dim 3 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 800 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= WgradRowBroadcast2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin s -Pout s -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 800 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= WgradColBroadcast2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin s -Pout s -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 800 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= WgradRowReduction2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin s -Pout s -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 800 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= WgradColReduction2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin s -Pout s -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 800 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= WgradResidual2D_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin s -Pout s -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 800 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= WgradResidual2D_no_virtual_abstract -dimA 176,80,34,34 -filtA 240,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin s -Pout s -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 800 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine FORT_CUTLASS_7X -jsonTestName= ConvRelu_abstract -dimA 63,80,56,56 -filtA 272,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -engineCfgSweep 1 -knobSplitKSlices= 1 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine FORT_CUTLASS_7X -jsonTestName= DgradDrelu_abstract -dimA 63,80,56,56 -filtA 272,80,1,1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -formatAll 1 -rtol 5e-3 -atol 5e-3 -minDevVer 700 -engineCfgSweep 1 -knobSplitKSlices= 1 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine FORT_CUTLASS_7X -jsonTestName= Matmul_abstract -kv=gemm_B :1 -kv=gemm_M :64 -kv=gemm_N :64 -kv=gemm_K :4096 -kv=gemm_layout_A :ROW_MAJOR -kv=gemm_layout_B :ROW_MAJOR -kv=gemm_layout_C :ROW_MAJOR -kv=Tin :half -kv=Tcomp :float -kv=Tout :half -rtol 5e-3 -atol 5e-3 -minDevVer 700 -engineCfgSweep 1 -knobSplitKSlices= 2 -S -b -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvBiasRelu_abstract -Pcomp s -Pin s -Pout s -dimA 5,32,32,32 -filtA 32,32,3,3 -dimOut 5,32,32,32 -padA 1,1 -convStrideA 1,1 -dilationA 1,1 -x -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvBias_abstract -Pcomp s -Pin s -Pout s -dimA 5,32,32,32 -filtA 32,32,3,3 -dimOut 5,32,32,32 -padA 1,1 -convStrideA 1,1 -dilationA 1,1 -x -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvBiasSoftsign_abstract -Pcomp s -Pin s -Pout s -dimA 8,256,200,336 -filtA 256,256,3,3 -dimOut 8,256,200,336 -padA 1,1 -convStrideA 1,1 -dilationA 1,1 -x -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvRelu_abstract1 -x -Pcomp s -Pin s -Pout s -convStrideA 1,1 -dilationA 1,1 -dimA 4,32,32,32 -filtA 32,32,3,3 -dimOut 4,32,30,30 -formatAll 1 -padA 0,0 -atol 2.5e-03 -rtol 2.5e-03 -minDevVer 750 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvScaleBiasRelu_inputType_abstract -dimA 32,32,7,7 -filtA 32,32,1,1 -Pin s -Pout s -Pcomp s -formatAll 1 -x -atol 2.5e-03 -rtol 2.5e-03 -kv=ScaleB_type :float -kv=ScaleY_type :float -kv=BiasB_type :float -kv=AddY_type :float -kv=ReluY_type :float -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvAddRelu0_fp32_fp32_fp32_swapXB -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= complex_graph_fp32_fp32_fp32 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= DgradDiffReductionCol2D_abstract -x -Pcomp s -Pin h -Pout h -convStrideA 2,2 -dilationA 1,1 -dimA 1,8,8,8 -filtA 8,8,3,3 -dimOut 1,8,3,3 -formatAll 1 -padA 0,0 -atol 2.5e-03 -rtol 2.5e-03 -kv=reduce_Op :CUDNN_REDUCE_TENSOR_ADD -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= DgradReductionFull_abstract -x -Pcomp s -Pin s -Pout s -convStrideA 2,2 -dilationA 1,1 -dimA 4,32,32,32 -filtA 32,32,3,3 -dimOut 4,32,15,15 -formatAll 1 -padA 0,0 -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= DgradRelu_abstract -x -Pcomp s -Pin s -Pout s -convStrideA 1,1 -dilationA 1,1 -dimA 4,32,32,32 -filtA 32,32,3,3 -dimOut 4,32,30,30 -formatAll 1 -padA 0,0 -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= DgradBiasRelu_abstract -x -Pcomp s -Pin s -Pout s -convStrideA 1,1 -dilationA 1,1 -dimA 4,32,32,32 -filtA 32,32,3,3 -dimOut 4,32,30,30 -formatAll 1 -padA 0,0 -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvRelu_not_virtual_abstract -dim 3 -x -Pcomp s -Pin s -Pout s -dimA 32,32,7,7,7 -filtA 32,32,1,1,1 -formatAll 1 -atol 5e-3 -rtol 5e-3 -minDevVer 800 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= Conv3dMul0_fp32_fp32_fp32 -rtol 5e-3 -atol 5e-3 -minDevVer 800 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvAddReluMulScalarBroadcast_abstract -x -Pin h -Pout s -Pcomp s -dimA 4,32,32,32 -filtA 32,32,3,3 -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MatmulBias_abstract -gemm_B =1 -gemm_M =64 -gemm_N =64 -gemm_K =64 -gemm_layout_A =ROW_MAJOR -gemm_layout_B =ROW_MAJOR -gemm_layout_C =ROW_MAJOR -Tin =half -Tcomp =float -Tstore =half -Tout =half -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MatmulAdd_abstract -gemm_B =1 -gemm_M =64 -gemm_N =64 -gemm_K =64 -gemm_layout_A =ROW_MAJOR -gemm_layout_B =ROW_MAJOR -gemm_layout_C =ROW_MAJOR -Tin =half -Tcomp =half -Tout =half -rtol 1e-2 -atol 1e-2 -minDevVer 700 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MatmulAdd_abstract_nonVirtualC -gemm_B =1 -gemm_M =64 -gemm_N =64 -gemm_K =64 -gemm_layout_A =ROW_MAJOR -gemm_layout_B =ROW_MAJOR -gemm_layout_C =ROW_MAJOR -Tin =half -Tcomp =half -Tout =half -rtol 1e-2 -atol 1e-2 -minDevVer 700 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MatMulAct_abstract -Tin =half -Tout =half -Tcomp =float -gemm_B =1 -gemm_M =64 -gemm_K =64 -gemm_layout_A =ROW_MAJOR -gemm_N =64 -gemm_layout_B =ROW_MAJOR -gemm_layout_C =ROW_MAJOR -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MatMulRowBias_abstract -Tin =half -Tout =half -Tcomp =float -gemm_B =1 -gemm_M =64 -gemm_K =64 -gemm_layout_A =ROW_MAJOR -gemm_N =64 -gemm_layout_B =ROW_MAJOR -gemm_layout_C =ROW_MAJOR -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= WgradRelu_abstract -x -Pcomp s -Pin s -Pout s -convStrideA 1,1,1 -dim 3 -dilationA 1,1,1 -dimA 4,8,32,32,32 -filtA 8,8,1,1,1 -dimOut 4,8,32,32,32 -formatAll 1 -padA 0,0,0 -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvReductionCol2D_virtual_abstract -Pcomp s -Pin h -Pout h -dimA 32,32,7,7 -filtA 256,32,1,1 -formatAll 1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -rtol 2.5e-3 -atol 2.5e-3 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvReductionColRow2D_virtual_abstract -Pcomp s -Pin h -Pout h -dimA 32,32,7,7 -filtA 256,32,1,1 -formatAll 1 -x -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -rtol 2.5e-3 -atol 2.5e-3 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MultiReduction_abstract -dimA 408,256,14,14 -dimOut 1,1,1,1 -Pin h -Pout s -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= AbsReductionFull0 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MatMulReductionCol_abstract -Tin =half -Tout =half -Tcomp =float -outType =float -gemm_B =1 -gemm_M =64 -gemm_K =64 -gemm_layout_A =ROW_MAJOR -gemm_N =64 -gemm_layout_B =ROW_MAJOR -gemm_layout_C =ROW_MAJOR -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MatMulRowReduction_NN_N_abstract -kv=Tcomp :float -atol 2.5e-03 -rtol 2.5e-03 -kv=Tin :float -kv=gemm_B :1 -kv=gemm_M :64 -kv=gemm_K :64 -kv=gemm_layout_A :ROW_MAJOR -kv=gemm_N :64 -kv=gemm_layout_B :ROW_MAJOR -kv=Tstore :float -kv=gemm_layout_C :ROW_MAJOR -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Add_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= AddSquare_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Div_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Max_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Min_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Mul_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Sub_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Abs_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Ceil_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Cos_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Exp_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Floor_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Neg_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Sin_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-03 -jsonTestName= Erf_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -Pin h -Pout h -Pcomp s -dimA 1024,8,14,14 -atol 2.5e-03 -rtol 2.5e-02 -jsonTestName= Tan_abstract -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= Convert_one_abstract -dimA 1024,8,14,14 -Pin h -kv=typeY :half -atol 2.5e-03 -rtol 2.5e-02 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= Reduction_abstract -dimA 128,256,7,7 -dimOut 1,256,1,1 -Pin h -Pout s -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= Scale_abstract -dimA 1024,8,14,14 -Pin h -atol 2.5e-03 -rtol 2.5e-03 -kv=dimB :[1024,8,14,14] -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ScaleBiasAct_abstract -dimA 32,32,7,7 -Pin h -atol 2.5e-03 -rtol 2.5e-03 -kv=Scale_dim :[32,32,7,7] -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ScaleBiasReductionCol0 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ScaleBiasReductionRow0 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= DualScaleBiasAddRelu -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvBiasRelu0_fp16_fp32_fp16_not_virtual -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine FORT_CUTLASS_8X -jsonTestName= RNN_Relu_Cell_HSH -knobKernelCfg= 0 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvAbsCmpMul_abstract -x -Pin h -Pout s -Pcomp s -dimA 256,64,28,28 -filtA 64,64,3,3 -padA 1,1 -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine FORT_CUTLASS_8X -jsonTestName= BatchedPaddedMatMul_bcast_mul_reduction -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= GeluApproxFwd_fp32 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= GeluFwdComposed_fp32 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvSigmoid_abstract -x -Pcomp s -Pin h -Pout s -dimA 4,32,32,32 -filtA 32,32,3,3 -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvElu_abstract -x -Pcomp s -Pin h -Pout s -dimA 4,32,32,32 -filtA 32,32,3,3 -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvGelu_abstract -x -Pcomp s -Pin h -Pout s -dimA 4,32,32,32 -filtA 32,32,3,3 -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= DgradActivationBwd_abstract -dimA 4,32,32,32 -filtA 32,32,3,3 -formatAll 1 -x -atol 2.5e-03 -rtol 2.5e-03 -Pin s -Pout h -Pcomp s -kv=actBWD_mode :CUDNN_POINTWISE_RELU_BWD -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MatmulMainloopFusionAbs_abstract -Tin =half -Tout =float -gemm_B =3 -gemm_M =256 -gemm_N =256 -gemm_K =128 -gemm_layout_A =ROW_MAJOR -gemm_layout_B =COL_MAJOR -gemm_layout_C =ROW_MAJOR -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    # TODO(@mbreughe): only passes in >= 9.1.0
    #python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MatmulMainloopFusionScale_abstract -Tin =half -Tout =float -gemm_B =3 -gemm_M =256 -gemm_N =256 -gemm_K =128 -gemm_layout_A =ROW_MAJOR -gemm_layout_B =COL_MAJOR -gemm_layout_C =ROW_MAJOR -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= MatmulMainloopFusionFullOp_abstract -Tin =half -Tout =float -gemm_B =3 -gemm_M =256 -gemm_N =256 -gemm_K =128 -gemm_layout_A =ROW_MAJOR -gemm_layout_B =COL_MAJOR -gemm_layout_C =ROW_MAJOR -atol 2.5e-03 -rtol 2.5e-03 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= ConvAdd_abstract -x -dimA 8,64,64,64 -filtA 64,64,3,3 -padA 1,1 -convStrideA 1,1 -dilationA 1,1 -Pin s -Pcomp s -Pout s -rtol 5e-3 -atol 5e-3 -minDevVer 800 -formatAll 1 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= WgradAdd_abstract -x -dimA 8,64,64,64 -filtA 64,64,3,3 -padA 1,1 -convStrideA 1,1 -dilationA 1,1 -Pin s -Pcomp s -Pout s -rtol 5e-3 -atol 5e-3 -minDevVer 800 -formatAll 1 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= DgradAdd_abstract -x -dimA 8,64,64,64 -filtA 64,64,3,3 -padA 1,1 -convStrideA 1,1 -dilationA 1,1 -Pin s -Pcomp s -Pout s -rtol 5e-3 -atol 5e-3 -minDevVer 800 -formatAll 1 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine -1 -jsonTestName= WgradReduction_abstract -x -dimA 8,64,64,64 -filtA 64,64,3,3 -padA 1,1 -convStrideA 1,1 -dilationA 1,1 -Pin s -Pcomp s -Pout s -rtol 5e-3 -atol 5e-3 -minDevVer 800 -formatAll 1 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= Conv_abstract -dimA 8,64,64,64 -filtA 64,64,3,3 -padA 1,1 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pcomp s -Pout h -rtol 5e-3 -atol 5e-3 -minDevVer 700 -formatAll 1 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= MatmulPointwiseUn_abstract -kv=PW_MODE :CUDNN_POINTWISE_RELU_FWD -gemm_B =1 -gemm_M =64 -gemm_N =64 -gemm_K =64 -gemm_layout_A =ROW_MAJOR -gemm_layout_B =ROW_MAJOR -gemm_layout_C =ROW_MAJOR -Tin =half -Tcomp =float -Tstore =half -Tout =half -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= MatmulPointwiseBin_abstract -kv=PW_MODE :CUDNN_POINTWISE_ADD -gemm_B =1 -gemm_M =64 -gemm_N =64 -gemm_K =64 -gemm_layout_A =ROW_MAJOR -gemm_layout_B =ROW_MAJOR -gemm_layout_C =ROW_MAJOR -Tin =half -Tcomp =float -Tstore =half -Tout =half -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= MatmulReduction_abstract -gemm_B =1 -gemm_M =64 -gemm_N =64 -gemm_K =64 -gemm_layout_A =ROW_MAJOR -gemm_layout_B =ROW_MAJOR -gemm_layout_C =ROW_MAJOR -Tin =half -Tcomp =float -Tout =float -Tstore =half -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -R graphRunner -backendEngine -1 -jsonTestName= MatmulRegressionGauntlet_abstract -gemm_B =1 -gemm_M =64 -gemm_N =64 -gemm_K =64 -gemm_layout_A =ROW_MAJOR -gemm_layout_B =ROW_MAJOR -gemm_layout_C =ROW_MAJOR -Tin =half -Tcomp =float -Tout =float -Tstore =half -rtol 5e-3 -atol 5e-3 -minDevVer 700 -S -b -serialization 0 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine 4 -engineCfgSweep 1 -knobSplitKSlices= 2 -jsonTestName= Dgrad_abstract -Pin h -Pout h -Pcomp s -dimA 1,32,32,32 -filtA 480,32,3,3 -formatAll 1 -padA 1,1 -dilationA 1,1 -convStrideA 1,1 -groupCount 1 -x -S -b -atol 2.5e-03 -rtol 2.5e-03 -minDevVer 900 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine 4 -engineCfgSweep 1 -knobSplitKSlices= 2 -jsonTestName= Wgrad_abstract -Pin h -Pout h -Pcomp s -dimA 1,480,32,32 -filtA 32,480,3,3 -formatAll 1 -padA 1,1 -dilationA 1,1 -convStrideA 1,1 -groupCount 1 -x -S -b -atol 2.5e-03 -rtol 2.5e-03 -minDevVer 900 -gpuRef -d 0
    # TODO(@mbreughe): only passes in >= 9.1.0
    #python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine 4 -engineCfgSweep 1 -knobSplitKSlices= 1 -jsonTestName= MatmulMainloopFusionRowBroadcast_abstract -S -b -kv=Tcomp :float -kv=Tin :half -kv=Tout :half -kv=gemm_B :4 -kv=gemm_M :1024 -kv=gemm_N :512 -kv=gemm_K :1024 -kv=gemm_layout_A :ROW_MAJOR -kv=gemm_layout_B :COL_MAJOR -kv=gemm_layout_C :ROW_MAJOR -atol 2.5e-03 -rtol 2.5e-03 -kv=NegB_type :half -kv=NegY_type :float -minDevVer 900 -gpuRef -d 0
    #python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine 4 -engineCfgSweep 1 -knobSplitKSlices= 1 -jsonTestName= MatmulMainloopFusionColBroadcast_abstract -S -b -kv=Tcomp :float -kv=Tin :half -kv=Tout :half -kv=gemm_B :4 -kv=gemm_M :1024 -kv=gemm_N :512 -kv=gemm_K :1024 -kv=gemm_layout_A :ROW_MAJOR -kv=gemm_layout_B :COL_MAJOR -kv=gemm_layout_C :ROW_MAJOR -atol 2.5e-03 -rtol 2.5e-03 -kv=NegB_type :float -kv=NegY_type :float -minDevVer 900 -gpuRef -d 0
    #python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine 4 -engineCfgSweep 1 -knobSplitKSlices= 1 -jsonTestName= MatmulMainloopMixedInput_abstract -S -b -kv=LoadA_type :int8 -kv=Tin1 :bf16 -kv=Tin2 :bf16 -kv=Tcomp :float -kv=gemm_B :4 -kv=gemm_M :1024 -kv=gemm_K :1024 -kv=gemm_layout_A :ROW_MAJOR -kv=gemm_N :512 -kv=gemm_layout_B :COL_MAJOR -kv=Tout :float -kv=gemm_layout_C :ROW_MAJOR -atol 2.5e-02 -rtol 2.5e-02 -minDevVer 900 -gpuRef -d 0
    python3 test/pycudnnTest/pycudnnTest.py -Dforce_jit_dbg= 1 -R graphRunner -backendEngine 4 -engineCfgSweep 1 -knobSplitKSlices= 1 -jsonTestName= ConvMainloopScaleBiasRelu_abstract -S -b -dimA 4,512,31,31 -filtA 512,512,3,3 -dimOut 4,512,29,29 -padA 0,0 -convStrideA 1,1 -dilationA 1,1 -Pin h -Pout h -Pcomp s -atol 2.5e-03 -rtol 2.5e-03 -minDevVer 900 -gpuRef -d 0

}

display_header
run_python_tests
